/**************************************************************************
 * Copyright (C) 2012-2021  Unisound
 *
 * DO NOT MODIFY.
 *
 * This file was generated by res_build_tool.py
 *
 **************************************************************************/
#ifndef INC_UNI_PCM_ARRY_H_
#define INC_UNI_PCM_ARRY_H_

typedef struct {
  uni_u32 number;
  uni_u32 offset;
  uni_u32 len;
}PCM_RESOURCE;

const PCM_RESOURCE g_pcm_arry[] = {
  {101, 0x0L, 0x682},
  {102, 0x6c0L, 0x6ca},
  {103, 0xdc0L, 0x321},
  {104, 0x1100L, 0x3b1},
  {105, 0x14c0L, 0x7a2},
  {106, 0x1c80L, 0x321},
};

#endif
