name: Build

on:
  push:
    branches:
      - 'release'
  pull_request:
    branches:
      - 'release'

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: andrewzzhu/w800-build:latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build
      run: cd solutions/unisound && make

    - name: Archive
      uses: actions/upload-artifact@v3
      with:
        name: uni_app
        path: solutions/unisound/out/unisound/uni_app.fls